source/coreApp/urls.py
from django.urls import path
from . import ajax
from django.views.decorators.csrf import csrf_exempt

app_name = "core"
urlpatterns = [
    path('ajax/save/', ajax.save, name="save"),
    path('ajax/mise_a_jour/', ajax.mise_a_jour, name="mise_a_jour"),
    path('ajax/supprimer/', ajax.supprimer, name="supprimer"),
    path('ajax/change_active/', ajax.change_active, name="change_active"),
    path('ajax/filter_date/', ajax.filter_date, name="filter_date"),
    path('ajax/session/', csrf_exempt(ajax.session), name="session"),
    path('ajax/delete_session/', csrf_exempt(ajax.delete_session), name="delete_session"),
    path('ajax/change_language/', ajax.change_language, name="change_language"),

]

source/mainApp/urls.py
from django.urls import path

from . import views

app_name = "mainApp"
urlpatterns = [
    path('', views.main, name='main'),
    path('services/', views.services, name='services'),
    path('contacts/', views.contacts, name='contacts'),
    
    path('admin/', views.login_, name='login'),
    path('admin/login/', views.login_, name='login'),
    path('admin/connexion/', views.connexion, name='connexion'),
    
    path('admin/liste/', views.liste, name='liste'),
    path('admin/user/<str:code>/', views.user, name='user'),
]

source/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('mainApp.urls')),
    path('root/', admin.site.urls),
    path('core/', include('coreApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/coreApp/models.py
import uuid
from django.db import models

# Create your models here.
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    protected = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_at']
        abstract = True

source/mainApp/models.py
import os
import uuid
from django.db import models
import qrcode
from coreApp.models import BaseModel
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save

from settings.settings import MEDIA_ROOT
# Create your models here.

class Newletter(BaseModel):
    nom       = models.CharField(max_length=255, null=True, blank=True)
    prenoms   = models.CharField(max_length=255, null=True, blank=True)
    subject   = models.CharField(max_length=255, null=True, blank=True)
    email     = models.CharField(max_length=255, null=True, blank=True)
    message   = models.TextField(default = "")



class Employe(BaseModel):
    nom           = models.CharField(max_length=255, null=True, blank=True)
    prenoms       = models.CharField(max_length=255,  null=True, blank=True)
    fonction      = models.CharField(max_length=255,  null=True, blank=True)
    code          = models.CharField(max_length=255,  null=True, blank=True)
    photo         = models.ImageField(max_length = 255, upload_to = "images/profiles/", default='images/profiles/default.png', null = True, blank=True)
    qrcode        = models.ImageField(max_length = 255, upload_to = "images/qrcodes/", default='images/qrcodes/default.png', null = True, blank=True)
    deleted       = models.BooleanField(default=False)
    created_at    = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.nom + '_' + self.prenoms





@receiver(pre_save, sender=Employe)
def _(sender, instance, **kwargs):
    if instance._state.adding:
        instance.code = str(uuid.uuid4()).split('-')[-1].upper()


# @receiver(post_save, sender=Employe)
# def _(sender, instance, created, **kwargs):
#     if created:
#         img = qrcode.make(f"https://www.gstechnologie.com/admin/user/{instance.id}/")
#         instance.qrcode = os.path.join(MEDIA_ROOT, f"images/qrcodes/{instance.id}.png")
#         img.save(f"media/images/qrcodes/{instance.id}.png")

source/mainApp/forms.py
from django.forms import ModelForm
from .models import *

        
class NewletterForm(ModelForm):
    class Meta:
        model = Newletter
        fields = "__all__"
        
        
class EmployeForm(ModelForm):
    class Meta:
        model = Employe
        fields = "__all__"
        

source/coreApp/views.py
from django.shortcuts import render

# Create your views here.

source/mainApp/views.py
from django.shortcuts import redirect, render
from annoying.decorators import render_to
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from mainApp.models import Employe
# Create your views here.


@render_to('mainApp/index.html')
def main(request):
    if request.method == "GET":
        ctx = {}
        return ctx
    
    
@render_to('mainApp/services.html')
def services(request):
    if request.method == "GET":
        ctx = {}
        return ctx
    
    
@render_to('mainApp/contacts.html')
def contacts(request):
    if request.method == "GET":
        ctx = {}
        return ctx
    
    
@render_to('mainApp/login.html')
def login_(request):
    if request.method == "GET":
        ctx = {}
        return ctx
    
    
    
@render_to('mainApp/login.html')
def connexion(request):
    if request.method == "POST":
        erreur = ""
        
        datas = request.POST
        user = authenticate(request, username=datas["username"], password=datas["password"])
        if user is None:
            erreur = "Username ou mot de passe incorrect !"
        else:
            login(request, user)
            return redirect('mainApp:liste')
     
        ctx = {
            "erreur": erreur
        }
        return ctx
    
    
@render_to('mainApp/liste.html')
def liste(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect('login')

        employes = Employe.objects.filter(deleted = False)
        ctx = {
            "employes": employes
        }
        return ctx
    
    
@render_to('mainApp/user.html')
def user(request, code):
    if request.method == "GET":
        employe = Employe.objects.filter(deleted = False, code = code).first()
        if employe is not None:
            ctx = {
                "employe": employe
            }
            return ctx

        else:
            return redirect("mainApp:main")

source/mainApp/templates/mainApp/blank.html
{% extends 'base/base.html' %}
{% load static %}


{% block "body" %}


{% endblock "body" %}

source/mainApp/templates/mainApp/contacts.html
{% extends 'base/base.html' %}
{% load static %}

{% block "title" %}#GST - Contactez-nous{% endblock "title" %}

{% block "body" %}

<!-- Start Header -->
<div class="fables-header fables-after-overlay">
    <div class="container"> 
      <h2 class="fables-page-title fables-second-border-color"><span class="fables-second-text-color">#GST</span> Contactez-nous</h2>
    </div>
</div>  
<!-- /End Header -->
     

     
<!-- Start page content --> 

    <div class="container"> 
        <div class="row overflow-hidden">
             <div class="col-12 col-md-4 text-center px-4 px-lg-5 my-4 my-lg-5 wow fadeInDown" data-wow-delay=".2s">
                  <div class="fables-second-border-color border fables-contact-block-border fables-rounded px-2">
                        <span class="fables-iconmap-icon fa-3x fables-second-text-color fables-contact-icon bg-white d-inline-block px-4"></span> 
                        <h2 class="font-16 semi-font fables-main-text-color my-3">Situation géographique</h2>
                        <p class="font-14 fables-forth-text-color">
                        Port-bout, rue de la baltique, Abidjan - Côte d'Ivoire</p>        
                  </div> 
             </div>
             <div class="col-12 col-md-4 text-center px-4 px-lg-5 my-4 my-lg-5 wow fadeInDown" data-wow-delay=".5s">
                  <div class="fables-second-border-color border fables-contact-block-border fables-rounded px-2">
                    <span class="fables-iconphone fa-3x fables-second-text-color fables-contact-icon bg-white d-inline-block px-4"></span>
                    <h2 class="font-16 semi-font fables-main-text-color my-3">Mail & Téléphone</h2>
                    <p class="font-14 fables-forth-text-color text-truncate">info@gstechnologie.com</p>
                    <p class="font-14 fables-forth-text-color">(+225) 27 215 438 05 / 27 215 425 45</p>
                 </div> 
             </div>
             <div class="col-12 col-md-4 text-center px-4 px-lg-5 my-4 my-lg-5 wow fadeInDown" data-wow-delay=".8s">
                 <div class="fables-second-border-color border fables-contact-block-border fables-rounded px-2">
                        <span class="fables-iconshare-icon fa-3x fables-second-text-color fables-contact-icon bg-white d-inline-block px-4"></span>
                        <h2 class="font-16 semi-font fables-main-text-color my-3">Restons connecter</h2>
                        <ul class="nav fables-contact-social-links"> 
                            <li><a href="#" target="_blank"><i class="fab fa-facebook-f fables-forth-text-color fa-fw"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-instagram fables-forth-text-color  fa-fw"></i></a></li> 
                            <li><a href="#" target="_blank"><i class="fab fa-twitter fables-forth-text-color    fa-fw"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-linkedin fables-forth-text-color   fa-fw"></i></a></li>
                        </ul>
                 </div> 
             </div>
        </div>        
        <div class="row mt-0 mb-4 my-md-3 overflow-hidden"> 
           <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <h1 class="font-weight-bold fables-main-text-color display-3 text-center title">Contactez-nous !</h1> 
                <p class="fables-contact-text fables-forth-text-color text-center">Une question, une préoccupation, un renseignement... Profitez de notre espace infoline pour obtenir toutes les informations nécessaires et répondre à vos questions </p>
           </div>  
                  
        </div><br><br>    
        <div class="row">
            <div class="col-12 wow fadeInLeft">
                <form  class="fables-contact-form formShamman" classname="NewletterForm">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control p-3 fables-rounded" name="nom"  placeholder="Nom">   
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control p-3 fables-rounded" name="prenoms"  placeholder="Prénoms">  
                        </div> 
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="email" class="form-control p-3 fables-rounded" name="email" placeholder="Adresse email"> 
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control p-3 fables-rounded" name="subject" placeholder="Object"> 
                        </div> 
                    </div> 
                    <div class="form-row"> 
                        <div class="form-group col-md-12">
                            <textarea class="form-control p-3 fables-rounded" name="message" placeholder="Ecrivez votre message ici" rows="4"></textarea>
                        </div> 
                    </div>
                    <div class="form-row">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn fables-second-background-color 
                            text-white fables-btn-rounded px-7 py-2 font-20">Envoyer le message</button>
                        </div>
                    </div>
                </form>                  
            </div>
            
        </div> <br><br>
    </div> 
<!-- /End page content -->

{% endblock "body" %}

source/mainApp/templates/mainApp/liste.html
{% extends 'base/base.html' %}
{% load static %}

{% block "title" %}#GST - Contactez-nous{% endblock "title" %}

{% block "body" %}

<!-- Start Header -->
<div class="fables-header fables-after-overlay">
    <div class="container"> 
      <h2 class="fables-page-title fables-second-border-color"><span class="fables-second-text-color">#GST</span> Administration</h2>
    </div>
</div>  
<!-- /End Header -->
     

     
<!-- Start page content --> 

    <div class="container"> 
           
        <div class="row mt-0 mb-4 my-md-3 overflow-hidden"> 
           <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <h1 class="font-weight-bold fables-main-text-color display-3 text-center title">Liste des employés !</h1> 
                <p class="fables-contact-text fables-forth-text-color text-center">Espace d'administration </p>
                <br>
                <div class="text-center">
                    <button class="btn fables-second-background-color 
                     text-white fables-btn-rounded px-7 py-2 font-20" data-toggle="modal" data-target="#modal-user"><i class="fa fa-plus"></i> Ajouter un nouveau employé</button>
                </div>
           </div>  
                  
        </div><br><br>    
        <div class="row g-5 text-left">
            <div class="bg-light mb-5 p-5 table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Code</th>
                            <th>Nom & prénoms</th>
                            <th>Poste</th>
                            <th colspan="3" style="width: 20px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employe in employes %}
                            <tr>
                                <td><img src="{{employe.photo.url}}" alt="{{employe.nom}} {{employe.prenoms}}" style="width:40px; height:40px"></td>
                                <td> {{employe.code}}</td>
                                <td>{{employe.nom}} {{employe.prenoms}}</td>
                                <td> {{employe.fonction}}</td>
                                <td><button data-toggle="modal" data-target="#modal-user-{{employe.id}}" class="btn  me-2"><i class="fa fa-edit"></i></button></td>
                                <td><button onclick="delete_password('EmployeForm', '{{employe.id}}')" class="btn  me-2 supprimer"><i class="fa fa-trash"></i></button></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div><br><br>
    </div> 
<!-- /End page content -->


<div class="modal fade" id="modal-user" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" >Nouvel employé</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" class="fables-contact-form formShamman" classname="EmployeForm">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control p-3 fables-rounded" required name="nom" placeholder="Nom">   
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control p-3 fables-rounded" required name="prenoms" placeholder="Prénoms">  
                        </div> 
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-9">
                            <input type="text" class="form-control p-3 fables-rounded" required name="fonction" placeholder="Fonction ou poste"> 
                        </div> 
                        <div class="col-md-3 form-group">
                            <img style="height: 100px; width: 100%; margin-bottom: 10px" src="" class="img-thumbnail logo">
                             <input class="hide" type="file" name="photo">
                             <button type="button" class="btn btn-sm bg-purple pull-right btn_image"><i class="fa fa-image"></i> Ajouter image</button>
                         </div>
                    </div> 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary">Ajouter l'employé</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% for employe in employes %}
    <div class="modal fade" id="modal-user-{{employe.id}}" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" >Modification employé</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="POST" class="fables-contact-form formShamman" classname="EmployeForm">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control p-3 fables-rounded" value="{{employe.nom}}" required name="nom" placeholder="Nom">   
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control p-3 fables-rounded" value="{{employe.prenoms}}" required name="prenoms" placeholder="Prénoms">  
                            </div> 
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-9">
                                <input type="text" class="form-control p-3 fables-rounded" value="{{employe.fonction}}" required name="fonction" placeholder="Fonction ou poste"> 
                            </div> 
                            <div class="col-md-3 form-group">
                                <img style="height: 100px; width: 100%; margin-bottom: 10px" src="{{employe.photo.url}}" class="img-thumbnail logo">
                                <input class="hide" type="file" name="photo">
                                <button type="button" class="btn btn-sm bg-purple pull-right btn_image"><i class="fa fa-image"></i> Ajouter image</button>
                            </div>
                        </div> 
                    </div>
                    <div class="modal-footer">
                        <input type="hidden" name="id" value="{{employe.id}}">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-primary">Valider le changement</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock "body" %}

source/mainApp/templates/mainApp/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block "title" %}#GST - Contactez-nous{% endblock "title" %}

{% block "body" %}

<!-- Start Header -->
<div class="fables-header fables-after-overlay">
    <div class="container"> 
      <h2 class="fables-page-title fables-second-border-color"><span class="fables-second-text-color">#GST</span> Administration</h2>
    </div>
</div>  
<!-- /End Header -->
     

     
<!-- Start page content --> 

    <div class="container"> 
           
        <div class="row mt-0 mb-4 my-md-3 overflow-hidden"> 
           <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <h1 class="font-weight-bold fables-main-text-color display-3 text-center title">Connectez-vous !</h1> 
                <p class="fables-contact-text fables-forth-text-color text-center">Espace d'administration </p>
           </div>  
                  
        </div><br><br>    
        <div class="row">
            <div class="col-2 "></div>
            <div class="col-8 wow fadeInLeft">
                <form class="fables-contact-form" method="POST" action="{% url 'mainApp:connexion' %}">
                    {% csrf_token %}
                  <div class="form-row">
                      <div class="form-group col-md-6">
                          <input type="text" class="form-control p-3 fables-rounded" name="username"  placeholder="username">   
                      </div>
                      <div class="form-group col-md-6">
                          <input type="password" class="form-control p-3 fables-rounded" name="password"  placeholder="mot de passe">  
                      </div> 
                  </div>
                  <p class="text-center text-danger">{{erreur}}</p><br>
                  <div class="form-row">
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn fables-second-background-color 
                         text-white fables-btn-rounded px-7 py-2 font-20"><i class="fa fa-lock"></i> Connexion</button>
                    </div>
                  </div>
                </form>                  
            </div>
            
        </div> <br><br>
    </div> 
<!-- /End page content -->

{% endblock "body" %}

source/mainApp/templates/mainApp/user.html
{% extends 'base/base.html' %}
{% load static %}

{% block "title" %}#GST - Contactez-nous{% endblock "title" %}

{% block "body" %}

<!-- Start Header -->
<div class="fables-header fables-after-overlay">
    <div class="container"> 
      <h2 class="fables-page-title fables-second-border-color"><span class="fables-second-text-color">#GST</span> Bagde - Vérification</h2>
    </div>
</div>  
<!-- /End Header -->
     

     
<!-- Start page content --> 

    <div class="container"> 
        <br><br>  
        <div class="row mt-0 mb-4 my-md-3 overflow-hidden"> 
           <div class="col-12 col-sm-6 col-md-4 ">
                <img class="img-thumbnail" src="{{employe.photo.url}}" alt="{{employe.nom}} {{employe.prenoms}}" style="width: auto">
           </div> 

           <div class="col-12 col-sm-6 col-md-8 ">
               <h3 class="fables-main-text-color title">{{employe.code}}</h3> <br>
                <h1 class="font-weight-bold fables-main-text-color display-4 title">{{employe.nom}} {{employe.prenoms}}</h1> 
                <h2 class="fables-main-text-color title">{{employe.fonction}}</h2> 
                <h4 class="fables-main-text-color title">{{employe.contact}}</h4> 
                <br>
                <h5 class=" fables-main-text-color title"><i class="fa fa-phone"></i> +225 07 091 776 31</h5> 
                <br>
                <h5 class="fables-main-text-color title"><i class="fa fa-envelope"></i> info@gstechnologie.com </h5> 
               
                <br>
                <p class="fables-contact-text fables-forth-text-color">Il fait bien partir de notre équipe ! </p>
            </div>  
                  
        </div><br><br>    
    
    </div> 
<!-- /End page content -->

{% endblock "body" %}

source/templates/extra/empty.html
{% load static %} 
{% load i18n %}      

<div class="text-center" style="padding-top: 5rem;">
    <img src="{% static 'dist/images/empty.gif' %}" alt="" style="width: 350px;"><br>
    <h1 class="text-center text-muted">{% translate "Rien pour le moment !" %}</h1>
</div>

source/templates/partials/footer.html
<div class="fables-footer-image fables-after-overlay white-color py-4 py-lg-5 bg-rules">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-2 mb-5 text-center">
                <h2 class="font-30 semi-font mb-5">Recevez notre actualité</h2>
                <form class="form-inline position-relative"> 
                  <div class="form-group fables-subscribe-formgroup"> 
                    <input type="email" class="form-control fables-subscribe-input fables-btn-rouned" placeholder="Votre adresse email">
                  </div>
                  <button type="submit" class="btn fables-second-background-color fables-btn-rouned fables-subscribe-btn">S'abonner</button>
                </form>
                
            </div>
            <div class="col-12 col-lg-4 mb-4 mb-lg-0">
                <h2 class="font-20 semi-font fables-second-border-color border-bottom pb-3">GST</h2>
                <p class="font-15 fables-third-text-color">
                    GST est une entreprise spécialisée dans la fibre optique, les réseaux et les solutions sur mesure. Grâce à une expertise approfondie, nous délivrons des résultats exceptionnels et durables, bâtissant la confiance de nos clients. Notre portfolio diversifié témoigne de projets réussis, allant de la connectivité de pointe à la conception de plateformes numériques performantes. <br><br>
                     Nous croyons en des partenariats durables, en plaçant la satisfaction de nos clients au cœur de nos priorités. Notre engagement envers l'excellence continue de façonner le paysage dynamique des TIC.
                </p> 
                
            </div>
             
            <div class="col-12 col-sm-6 col-lg-4">
                <h2 class="font-20 semi-font fables-second-border-color border-bottom pb-3">Contactez-nous</h2>
               <div class="my-3">
                    <h4 class="font-16 semi-font"><span class="fables-iconmap-icon fables-second-text-color pr-2 font-20 mt-1 d-inline-block"></span> Siège social</h4>
                    <p class="font-14 fables-fifth-text-color mt-2 ml-4">Rue de la baltique, Port-Bouët, Abidjan</p>
                </div>
                <div class="my-3">
                    <h4 class="font-16 semi-font"><span class="fables-iconphone fables-second-text-color pr-2 font-20 mt-1 d-inline-block"></span> Appelez-nous </h4>
                    <p class="font-14 fables-fifth-text-color mt-2 ml-4">(+225) 27 215 438 05 / 27 215 425 45</p>
                </div>
                <div class="my-3">
                    <h4 class="font-16 semi-font"><span class="fables-iconemail fables-second-text-color pr-2 font-20 mt-1 d-inline-block"></span> E-mail </h4>
                    <p class="font-14 fables-fifth-text-color mt-2 ml-4">info@gstechnologie.com.com</p>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-4">
                <h2 class="font-20 semi-font fables-second-border-color border-bottom pb-3 mb-3">PLAN DE NOTRE SITE</h2>
                <ul class="nav fables-footer-links">
                    <li><a href="{% url "mainApp:main" %}">Acceuil </a></li>
                    <li><a href="{% url "mainApp:services" %}">Notre expertise</a></li>
                    <li><a href="{% url "mainApp:contacts" %}">Contactez-nous</a></li>
                </ul>
            </div>
                      
        </div> 
        
        </div>
</div>
<div class="copyright fables-main-background-color  mt-0 border-0 white-color">
        <ul class="nav fables-footer-social-links just-center fables-light-footer-links">
            <li><a href="" target="_blank"><i class="fab fa-google-plus-square"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-facebook"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-pinterest-square"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-twitter-square"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-linkedin"></i></a></li>
        </ul>
        <p class="mb-0">Copyright © GST 2023. Tous droits reservés.</p> 

</div>
    

source/templates/partials/header.html
{% load static %}

<!-- Start Top Header -->
<div class="fables-forth-background-color fables-top-header-signin">
    <div class="container">
        <div class="row" id="top-row">
            <div class="col-12 col-sm-2 col-lg-5">
                             
            </div>
            <div class="col-12 col-sm-5 col-lg-4 text-right">
                <p class="fables-third-text-color font-13"><span class="fables-iconphone"></span> Téléphone :  (+225) 27 215 438 05 / 27 215 425 45</p>
            </div>
            <div class="col-12 col-sm-5 col-lg-3 text-right">
                <p class="fables-third-text-color font-13"><span class="fables-iconemail"></span> Email: info@gstechnologie.com</p>
            </div>
            
        </div>
    </div>
</div>
 
<!-- /End Top Header -->


<div class="fables-navigation fables-main-background-color py-3 py-lg-0">
    <div class="container">
           <div class="row">
               <div class="col-12 col-md-10 pr-md-0">                       
                   <nav class="navbar navbar-expand-md btco-hover-menu py-lg-2">

                        <a class="navbar-brand fables-logo-brand pl-0" href="{% url 'mainApp:main' %}"><img style="height: 40px" src="{% static 'images/logo1.png' %}" alt="Fables Template" class="fables-logo"></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#fablesNavDropdown" aria-controls="fablesNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="fables-iconmenu-icon text-white font-16"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="fablesNavDropdown"> 

                            <ul class="navbar-nav mx-auto fables-nav">   
                                <li class="nav-item ">
                                    <a class="nav-link" href="{% url "mainApp:main" %}" id="sub-nav1" >Acceuil</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="{% url "mainApp:services" %}" >
                                        Notre expertise
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link" href="{% url "mainApp:contacts" %}" aria-haspopup="true" aria-expanded="false">
                                        Contactez-nous
                                    </a> 
                                </li>
                                
                            </ul> 

                </div>
            </nav>
               </div>
           </div>
    </div>
</div>